### ISSUE TITLE
Tracking issue for missing functionality in `muda`

### ISSUE THREAD

**Issue by amrbashir** [amrbashir/muda#5]
### Necessary:
- [X] `init_for_window`
- [X] `hide_for_window` - #8
- [X] `show_for_window` - #8
- [X] `remove_for_window` - #8
- [X] `Submenu` 
- [X] `MenuItem`
- [X] Accelerators
  - [X] Windows - #6
  - [X] Linux - #6
  - [X] macOS  - #12
- [x] `NativeMenuItem`
  - [X] Windows - #9 
  - [X] Linux - #9
  - [x] macOS - #14
- [x] `CheckMenuItem`
  - [x] Windows - #13
  - [x] Linux - #13
  - [x] macOS - #14 
- [ ] ~~Localized Labels~~
- [ ] Change native items labels
- [X] `Accelerator::from_str()` compatibility with current tao implementation - #17
  
### Extras
- [ ] `Menu::showContextMenu(window, x, y)`
  - [ ] Windows - Possible, use `TrackPopupMenu` from win32 apis
  - [ ] Linux - Possible, use `gtk_menu_popup_at_rect` from gtk
  - [ ] macOS - Possible, use `popUpMenuPositioningItem` from appkit
- [ ] `ImageMenuItem`
  - [ ] Windows
  - [ ] Linux
  - [ ] macOS
- [ ] `RadioMenuItem`
  - [ ] Windows
  - [ ] Linux
  - [ ] macOS

**Comment by martpie** [comment]
Looking forward! 🚀 Thank you so much for working on this!

**Comment by merryhime** [comment]
Regarding popupMenus on mac, consider [popUpMenuPositioningItem:atLocation:inView:](https://developer.apple.com/documentation/appkit/nsmenu/1518212-popupmenupositioningitem?language=objc).

**Comment by amrbashir** [comment]
Thank you, I updated the list
